model:
  output_dir: './afp_default/'
  kwargs:
    selection: 'afp'
    lex_eps_global: False
    lex_eps_dynamic: False
    islands: False
    num_islands: 10
    island_gens: 100
    verbosity: 1
    print_data: False
    elitism: True
    pHC_on: True
    prto_arch_on: True
    max_len: 64
    max_len_init: 20
    time_limit: 7200
    popsize: 100
    g: 250
    op_list: ['n', 'v', '+', '-', '*', '/', 'exp', 'log', '2', '3', 'sqrt', 'sin', 'cos']
    EstimateFitness: False
