model:
  output_dir: './afp_optuna/'
  optuna:
    optimize:
      n_trials: 100
      timeout: 84600 # 60 * 60 * 23.5
      n_jobs: -1
    popsize:
      low: 100
      high: 1000
    g:
      low: 250
      high: 2500
    op_list:
      choices: 
        - ['n', 'v', '+', '-', '*', '/', 'exp', 'log', '2', '3', 'sqrt']
        - ['n', 'v', '+', '-', '*', '/', 'exp', 'log', '2', '3', 'sqrt', 'sin', 'cos']
    stop_threshold: 
      low: 1.0e-10
      high: 0.01
  kwargs:
    selection: 'afp'
    lex_eps_global: False
    lex_eps_dynamic: False
    islands: False
    num_islands: 10
    island_gens: 100
    verbosity: 1
    print_data: False
    elitism: True
    pHC_on: True
    prto_arch_on: True
    max_len: 64
    max_len_init: 20
    time_limit: 7200
    EstimateFitness: False
